<?php

namespace ShoppingCartBundle\Repository;

/**
 * InvoiceBooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceBooksRepository extends \Doctrine\ORM\EntityRepository
{
}
